Repository Luodian/Otter, pull requests merged in 2023-06, with the labels that each got.

#137 [Doc] update demo page
  .gitignore
  flamingo/__init__.py
  flamingo/configuration_flamingo.py
  flamingo/converting_flamingo_to_pytorch.py
  flamingo/modeling_flamingo.py
  mimic-it/syphus/abstract_dataset.py
  mimic-it/syphus/datasets/fpv.py
  mimic-it/syphus/datasets/translate.py
  mimic-it/syphus/datasets/video.py
  mimic-it/syphus/file_utils.py
  mimic-it/syphus/main.py
  otter/__init__.py
  otter/configuration_otter.py
  otter/flamingo_pt2otter_hf.py
  otter/modeling_otter.py
  otter/otter_pt2otter_hf.py
  pipeline/conversation.py
  pipeline/eval/benchmark_otter.py
  pipeline/eval/classification.py
  pipeline/eval/eval_datasets.py
  pipeline/eval/evaluate.py
  pipeline/eval/imagenet_utils.py
  pipeline/eval/vqa_metric.py
  pipeline/mimicit_utils/arguments.py
  pipeline/mimicit_utils/input_dataset.py
  pipeline/mimicit_utils/mimicit_dataset.py
  pipeline/mimicit_utils/transforms.py
  pipeline/serve/cli.py
  pipeline/serve/controller.py
  pipeline/serve/gradio_patch.py
  pipeline/serve/gradio_web_server.py
  pipeline/serve/gradio_web_server_video.py
  pipeline/serve/model_worker.py
  pipeline/serve/serving_utils.py
  pipeline/serve/test_message.py
  pipeline/train/data.py
  pipeline/train/distributed.py
  pipeline/train/instruction_following.py
  pipeline/train/instruction_following_ddp.py
  pipeline/train/instruction_following_ds.py
  pipeline/train/train_utils.py
  pipeline/utils/apply_delta.py
  pipeline/utils/calculate_similarity.py
  pipeline/utils/cat_rank_feature.py
  pipeline/utils/convert_mmc4_to_wds.py
  pipeline/utils/featextrater_llm.py
  pipeline/utils/get_SN_train_data.py
  pipeline/utils/get_llava_image_data.py
  pipeline/utils/get_llava_interleaved_data.py
  pipeline/utils/get_llava_train_data.py
  pipeline/utils/get_partal_llava_train_data.py
  pyproject.toml
  xformers_model/clip.py
  xformers_model/llama.py
Labels: area:demo, priority:high, branch:ready to merge

#152 [Bug] fix special tokens
  pipeline/conversation.py
  pipeline/serve/gradio_web_server.py
  pipeline/serve/gradio_web_server_video.py
Labels: area:demo, branch:under review

#153 Convert it
  LICENSE
  README.md
  docs/demo.md
  docs/huggingface_compatible.md
  docs/model_card.md
  docs/server_host.md
  mimic-it/README.md
  mimic-it/convert-it/README.md
  mimic-it/convert-it/abstract_dataset.py
  mimic-it/convert-it/datasets/2d.py
  mimic-it/convert-it/datasets/3d.py
  mimic-it/convert-it/datasets/__init__.py
  mimic-it/convert-it/datasets/change.py
  mimic-it/convert-it/datasets/fpv.py
  mimic-it/convert-it/datasets/utils/scene_navigation_utils.py
  mimic-it/convert-it/datasets/utils/visual_story_telling_utils.py
  mimic-it/convert-it/datasets/video.py
  mimic-it/convert-it/image_utils.py
  mimic-it/convert-it/main.py
  mimic-it/docs/mimicit_logo.png
  mimic-it/syphus/abstract_dataset.py
  pipeline/demo/__init__.py
  pipeline/demo/otter_image.ipynb
  pipeline/demo/otter_video.ipynb
  pipeline/demo/otter_video.py
  pipeline/eval/benchmark_otter.py
  pipeline/eval/classification.py
  pipeline/eval/coco_metric.py
  pipeline/eval/eval_datasets.py
  pipeline/eval/evaluate.py
  pipeline/eval/imagenet_utils.py
  pipeline/eval/ok_vqa_utils.py
  pipeline/eval/vqa_metric.py
Labels: branch:developing, area:dataset

#176 [Improvement] Enhance image processing and memory efficiency - Do Not Merge Yet
  mimic-it/README.md
  mimic-it/convert-it/README.md
  mimic-it/convert-it/__init__.py
  mimic-it/convert-it/abstract_dataset.py
  mimic-it/convert-it/datasets/2d.py
  mimic-it/convert-it/datasets/3d.py
  mimic-it/convert-it/datasets/change.py
  mimic-it/convert-it/datasets/fpv.py
  mimic-it/convert-it/datasets/utils/scene_navigation_utils.py
  mimic-it/convert-it/datasets/utils/visual_story_telling_utils.py
  mimic-it/convert-it/datasets/video.py
  mimic-it/convert-it/image_utils.py
  mimic-it/convert-it/main.py
  requirements.txt
Labels: branch:developing
