Repository Luodian/Otter, pull requests merged in 2023-08, with the labels that each got.

#232 [dataset] add CGD to AVAILABLE_DATASETS
  mimic-it/syphus/abstract_dataset.py
Labels: area:dataset

#235 [evaluation] evaluate otter
  pipeline/eval/__init__.py
  pipeline/eval/config.yaml
  pipeline/eval/eval_datasets.py
  pipeline/eval/evaluate.py
  pipeline/eval/models/open_flamingo.py
  pipeline/eval/models/otter.py
  pipeline/eval/run_eval_coco.sh
Labels: area:evaluation

#244 [model] Add support for Llama2, Palm, Cohere, Replicate Models - using litellm
  mimic-it/syphus/file_utils.py
  requirements.txt
Labels: branch:under review, area:dataset
